### ISSUE TITLE
Unit tests...!

### ISSUE THREAD

**Issue by rec** [testcaseone/vbat#4]
I saw some small changes I wanted to make but without a way to test their correctness, I'm loathe to do so.

A set of tests, perhaps not a huge set, would help catch lots of errors.  

You want to strike a balance between "lots of busywork" and "avoiding making terrible mistakes".

I could easily (as in 5 minutes) create an "empty" unit test which tested nothing, and then you could fill in the actual test cases.

It'd be also really good if you wanted to move it to numpy or something, because you can could check that it worked exactly the same with and without.

**Comment by testcaseone** [comment]
I tried and failed with the test case. I have no experience with this, would be nice if you take a look at what i did and explain to my what i did wrong and how it should be made :)
