### ISSUE TITLE
Rearranging  directory structure

### ISSUE THREAD

**Issue by testcaseone** [testcaseone/vbat#8]
We also have the Software for the serve controller (Arduino) and Stuff about the Hardware (circuit diagram and blue prints). So i guess we have to have another directory structure. Can we change the whole thing to something like this? And how to do this right? Do i just have to change it to this on my computer and push it? @rec 

Software/
....vbat/
........[...]
....vbat_servo_controller/
........[...]
Hardware/
....[...]

**Comment by rec** [comment]
Typically the top-level directory has almost nothing in it:  like this:  https://github.com/rec/grit

Then all the actual code lives in a `vbat/` subdirectory, with sub-sub-directories `vbat/servo_controller`, `vbat/hardware`, etc.

**Comment by testcaseone** [comment]
@rec So, i tried to change the directory structure. Should have chosen the same username as on reddit. It went horribly wrong and destroyed my local copy. Any chance you could do that too?

**Comment by rec** [comment]
Up and ready!  But this seems to be fixed...?

I'm going to pull and see how it works today, stay tuned.

I'm on and off most of the afternoon (your evening) and much of tomorrow
day.


On Sat, Aug 29, 2015 at 8:27 AM, Tim <notifications@github.com> wrote:

> Closed #8 <https://github.com/testcaseone/vbat/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#event-395728043>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by rec** [comment]
So I'm a little confused about the current directory structure!
Particularly, you seem to have moved things into a new vbat subdirectory,
which contains a subdirectory vbat...


Can you tell me what Python package hierarchy you are wanting to have?

In other words, within Python, what are the names of the classes going to
be?


(Also, you shouldn't use - inside Python file names, because then you can't
refer to them from other Python files...)

On Sat, Aug 29, 2015 at 11:43 AM, Tom Swirly <tom@swirly.com> wrote:

> Up and ready!  But this seems to be fixed...?
>
> I'm going to pull and see how it works today, stay tuned.
>
> I'm on and off most of the afternoon (your evening) and much of tomorrow
> day.
>
>
> On Sat, Aug 29, 2015 at 8:27 AM, Tim <notifications@github.com> wrote:
>
>> Closed #8 <https://github.com/testcaseone/vbat/issues/8>.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/testcaseone/vbat/issues/8#event-395728043>.
>>
>
>
>
> --
>      /t
>
> http://radio.swirly.com - art music radio 24/7 366/1000
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
> Also, you shouldn't use - inside Python file names, because then you can't
refer to them from other Python files

Oh, right, i had that problem before and forgot about that. 
vbat is the name of the project, i just named the program that later does all the work after that. I had in mind i needed the last vbat subdirectory for the test, but i could be wrong, something went wrong again as i tried to change the directories, the test doesn't work anymore too.

I'm out this evening, it might ask to much here, but could you maybe change things so the kind of make sense? What i made before was way smaller and i never learned what's the best way to organize projects or name my classes. 

What we have is the program vbat-config.py, where you create the files that vbat.py uses to extract the GPS values and height. And in "servo_controller" is the Arduino code to move the servos to the right position. You can rename anything you like to make more sense if you want to, i would be grateful. You can also pull what you make direct into the project, you should be able to do that, right?

**Comment by rec** [comment]
The test never worked for me!  :-)

But you've added a bunch of data files so it might work now.  Or at least,
I can fix it up and tell you what to do.


So here's a question to you before we start... how much bigger do you think
this project is going to get, compared to now?

As it is, it would really make sense to have very few subdirectories, all
the Python in the top level and that sort of thing.  If you were going to
have twice as much code, you might start to want to create
subdirectories... if you were going to have four times as much, definitely.




On Sat, Aug 29, 2015 at 12:09 PM, Tim <notifications@github.com> wrote:

> Also, you shouldn't use - inside Python file names, because then you can't
> refer to them from other Python files
>
> Oh, right, i had that problem before and forgot about that.
> vbat is the name of the project, i just named the program that later does
> all the work after that. I had in mind i needed the last vbat subdirectory
> for the test, but i could be wrong, something went wrong again as i tried
> to change the directories, the test doesn't work anymore too.
>
> I'm out this evening, it might ask to much here, but could you maybe
> change things so the kind of make sense? What i made before was way smaller
> and i never learned what's the best way to organize projects or name my
> classes.
>
> What we have is the program vbat-config.py, where you create the files
> that vbat.py uses to extract the GPS values and height. And in
> "servo_controller" is the Arduino code to move the servos to the right
> position. You can rename anything you like to make more sense if you want
> to, i would be grateful. You can also pull what you make direct into the
> project, you should be able to do that, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136005593>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Not much bigger, we just have to add plans for the Hardware and the comport stuff for the communication to the arduino

**Comment by testcaseone** [comment]
You need to habe a Webcam on your PC, and i use Linux, it might be that i used some OS operations that only work with linux

**Comment by rec** [comment]
All right, then, I think everything should be at the top level!

I'll prepare a branch - amongst various weekend chores, there might be a
delay :-) and then send a pull request!

On Sat, Aug 29, 2015 at 1:00 PM, Tim <notifications@github.com> wrote:

> Not much bigger, we just have to add plans for the Hardware and the
> comport stuff for the communication to the arduino
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136009554>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by rec** [comment]
For this sort of thing, the Mac is often compatible, but if it doesn't I
have a Linux machine I can switch to with a keystroke, and also a bunch of
version 1 Raspberry Pi's I can try.

On Sat, Aug 29, 2015 at 1:02 PM, Tim <notifications@github.com> wrote:

> You need to habe a Webcam on your PC, and i use Linux, it might be that i
> used some OS operations that only work with linux
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136009652>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Thats great, would be hard to change the code if you can't test it :)

**Comment by rec** [comment]
Indeed!

In fact, I'm pretty sure I could just drop in the multiprocessing - but
then how would I know it worked?  My theory is that once we have decent
tests, the mp stuff will be just a few lines.



On Sat, Aug 29, 2015 at 1:10 PM, Tim <notifications@github.com> wrote:

> Thats great, would be hard to change the code if you can't test it :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136009979>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
If you want i could change the program tomorrow so that you don't need a Webcam and if needed i can make sure it runs in Windows. If it's the test itself that doesn't work, you can just Start it with vbat.py -n zz -i test.jpg vor jpeg and compare the output with the data in the image

**Comment by rec** [comment]
I don't have access to Windows right now!  :-)


I actually think there is enough code already to warrant keeping the
subdirectory, so I'll just clean it out and add a couple of "top level
programs" to preserve what's there.  There will be little change...


So what are these files?
https://github.com/testcaseone/vbat/tree/master/vbat/saves/zz




On Sat, Aug 29, 2015 at 1:24 PM, Tim <notifications@github.com> wrote:

> If you want i could change the program tomorrow so that you don't need a
> Webcam and if needed i can make sure it runs in Windows. If it's the test
> itself that doesn't work, you can just Start it with vbat.py -n zz -i
> test.jpg vor jpeg and compare the output with the data in the image
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136012833>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
zz is one if the saves. The .COO files has the coordinates of the Position were the Characters in the image are and the .template file hast templates oft the Charakters it's trying to find. In the folder images are the images wie needed to create the files, same goes for the temp folder

**Comment by testcaseone** [comment]
You can create More saves for different planes, so there might be different stuff in saves

**Comment by rec** [comment]
You shouldn't be creating them in the Python directory!  :-)

I'm going to move them as part of the branch.  We can discuss...

On Sat, Aug 29, 2015 at 2:10 PM, Tim <notifications@github.com> wrote:

> You can create More saves for different planes, so there might be
> different stuff in saves
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136021133>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by rec** [comment]
Also - should you actually be checking those files in?  I mean, aren't they
data files that will be different for each person?

On Sat, Aug 29, 2015 at 2:12 PM, Tom Swirly <tom@swirly.com> wrote:

> You shouldn't be creating them in the Python directory!  :-)
>
> I'm going to move them as part of the branch.  We can discuss...
>
> On Sat, Aug 29, 2015 at 2:10 PM, Tim <notifications@github.com> wrote:
>
>> You can create More saves for different planes, so there might be
>> different stuff in saves
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136021133>.
>>
>
>
>
> --
>      /t
>
> http://radio.swirly.com - art music radio 24/7 366/1000
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Yes they are, but to check if the program is working you need the files, so you don't have to create a sample by your self

**Comment by testcaseone** [comment]
Yes they are different for each person I mean, not that they should be checked in

**Comment by rec** [comment]
(Almost done with the rearrangement and learned something too...)


So it seems to me that you might have two things glued on top of each other!

Seems to me there need to be two different directories...?

One is the "demo data directory" that you ship with the program to make
sure it works.

The other one is the "user's data directory" where they store the actual
results for *their* specific program.

These need to go in different places or users will overwrite the tests...


On Sat, Aug 29, 2015 at 2:21 PM, Tim <notifications@github.com> wrote:

> Yes they are different for each person I mean, not that they should be
> checked in
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136021599>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000

**Comment by testcaseone** [comment]
Oh okay, right. So you could always test with a sample regardless of what files you tried to create. That's a good idea

**Comment by testcaseone** [comment]
There is also in the arduino directory a program to test the motors. Don't know if there is a better place for that

**Comment by rec** [comment]
We can deal with that separately!  :-)

On Sat, Aug 29, 2015 at 2:55 PM, Tim <notifications@github.com> wrote:

> There is also in the arduino directory a program to test the motors. Don't
> know if there is a better place for that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/testcaseone/vbat/issues/8#issuecomment-136025076>.
>



-- 
     /t

http://radio.swirly.com - art music radio 24/7 366/1000
